# Generated by Django 5.0.6 on 2024-06-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredientes',
            field=models.CharField(default='Valor padrão', max_length=255),
        ),
    ]
